name: 'Storybook â€” Build & Deploy'

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    name: 'Build + Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to pinata-storybook
        run: |
          mkdir -p docs && cd docs
          echo "world" >> hello.txt
          git config --global user.email "gina@example.com"
          git config --global user.name "Gina"
          git fetch
          git add . && git commit -m 'Deploy from Pinata' && git push --force origin/gh-pages

